version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      
  node-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: 
          command: npm test
          working_directory: ./server
  
  react-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client       
      - run:
          command: npm test
          working_directory: ./client
  
  docker-publish:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "$DOCKER_PASS" | docker login -u "akrason" --password-stdin
            sudo docker build ./server -t akrason/ask-cicd/node-svr
            sudo docker push akrason/ask-cicd/node-svr
      - run:
          command: |
            echo "$DOCKER_PASS" | docker login -u "akrason" --password-stdin
            sudo docker build ./client -t akrason/ask-cicd/cra-client
            sudo docker push akrason/ask-cicd/cra-client
      - run:
          command: |
            echo "$DOCKER_PASS" | docker login -u "akrason" --password-stdin
            sudo docker build ./db -t akrason/ask-cicd/node-react-db
            sudo docker push akrason/ask-cicd/node-react-db
workflows:
    build-and-test:
      jobs:
        - build
        - node-server:
            filters:
              branches:
                only:
                  - master
            requires:
              - build
        - react-client:
            filters:
              branches:
                only:
                  - master
            requires:
              - build
        - docker-publish:
            filters:
              branches:
                only:
                  - master
            requires:
              - react-client
              - node-server
